### ISSUE TITLE
[Bug] Firefox menu disappearrs

### ISSUE THREAD

**Issue by kevlogan90** [lestcape/Global-AppMenu#11]
This issue seems to be similar to [#9] (https://github.com/lestcape/Global-AppMenu/issues/9). The menu for Firefox disappears after some time. Using cinnamon 2.6.7.

**Comment by lestcape** [comment]
Hey.. jejeje read the applet description...

**Comment by kevlogan90** [comment]
Sorry

**Comment by lestcape** [comment]
Not matter is in fact an issue....

**Comment by kevlogan90** [comment]
So did you not port ubuntu's global menu to work on cinnamon? It doesn't seem to happen with gedit, which also needs some plugin to work like firefox. Is there a difference between those?

**Comment by lestcape** [comment]
No, what i do is support for read the dbusmenu (GTK and KDE). If you use the ubuntu code for export the menu or other is not transcendental for the applet. I also do more things because the ubuntu code require some environment configuration. This could be set by user, but in the ubuntu case I do this automatically as is the most important (because can be installed on mint).

**Comment by lestcape** [comment]
Gedit is reding using the GTK way(GTK the GApplication API https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI), Firefox the KDE way(KDE use the Registrar iface). registrar iface was depveloment by canonical, but is used outside ubuntu as an standar.

**Comment by kevlogan90** [comment]
I see, so the KDE way is causing the issue. I wish I could help, but I don't know much beyond basic C++ and Python. I'm trying to find good resources online to start learning JS, I'm just starting to look at the cinnamon developer wiki, which is really great. It helps a lot. I would like to be able to contribute to development eventually.

The work done on this applet so far is really great, and I know people will enjoy it, so thanks for all the hard work!

**Comment by lestcape** [comment]
Both are problematics... The kde way is taking for the https://github.com/rgcjonas/gnome-shell-extension-appindicator extension and gtk way is developed by me using this specification https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI As you can see the specification it required that you open the connection the same amount of times that you close the connection and this only be guaranteed with a recent change in cinnamon (https://github.com/linuxmint/Cinnamon/commit/a5dd0778078fa0ccdfdf7056a5a0299586dbe357#commitcomment-11469634)... As now, there are a signal that i can capture when cinnamon will restart. Older cinnamon versions can not support this. There are no way to check when cinnamon is restarting and i lost the counting... The solution was close the connection when i open it, but open office change the menu dynamically, and i don't have a way to listen it, as the connection is closed. See the bug here:
https://github.com/lestcape/Global-AppMenu/issues/9

The solution was partially, and was produce more updates when the menu will be open, but this is playing with time as i don't sure when Open Office emit an update. Apparently is faster and for this reason is working, but is not warranty.

I see that you recently add another issue and i think is because what i explain above about the gtk update.
https://github.com/lestcape/Global-AppMenu/issues/12

**Comment by lestcape** [comment]
Firefox is fixed.
