### ISSUE TITLE
Thunderbird menu

### ISSUE THREAD

**Issue by dmitry-ilin** [lestcape/Global-AppMenu#13]
Hi,

Many thanks for this applet. You did a great job! I found an issue with Thunderbird. The applet doesn't display thunderbird menu, but thunderbird native menu disappears. Could you please investigate it?

There is also one interesting point on it which may help a bit. If I'm restarting Cinnamon using "Alt+F2 -> r" the menu becomes visible in the applet.

I tried to debug it, but unfortunately I have a lack of knowledge in system programming. Thanks for your time.

**Comment by lestcape** [comment]
Yes, thunderbird appear to have the same problem that have firefox. Please see the description. I can not find a solution. Sorry.

**Comment by Meiden-fc** [comment]
Did you check the extra packages which are necessary for MATE?

http://www.webupd8.org/2014/12/get-global-menu-in-mate-18-with-topmenu.html

**Comment by lestcape** [comment]
@Meiden-fc do see my comments on this thread?

Is not interesting to me, how the menu will be exported. Is interesting to me how i can read the menu and interact with it. What i do, is not a patch for gtk or firefox and i will not do any of this. What i do, is read the menu structure if is available and is correctly. This is interesting to user (i'm not a user), because all packages that help to provide a dbus menu, will be an addition to what the cinnamon global menu can read. If they are standar (firefox and thunderbird clear are not standar), they require apparently more things that what i do. I will do it if i can know what more they require. Simple i don't know and not want tell me (and there are not any specification of this), so i can not do anything.

This sure will be interesting to you:

http://www.webupd8.org/2015/05/global-menu-applet-for-cinnamon-desktop.html

**Comment by lestcape** [comment]
Fixed here (also firefox): https://github.com/lestcape/Global-AppMenu/commit/962775a229f6cafdeaf89459f5b81331d257d7ab
