### ISSUE TITLE
Only shows title

### ISSUE THREAD

**Issue by Kat1031** [lestcape/Global-AppMenu#2]
Hello, I'm using Mint Rebecca with Cinnamon.
I just installed this, but it shows the window title on the panel, not the menu.
What I want is a global menu. Any suggestions?

Thanks.

![nomenu](https://cloud.githubusercontent.com/assets/8394389/7066614/f16e3e78-def6-11e4-84a0-1d2d33243ac4.png)

**Comment by lestcape** [comment]
Hi, of course there are a lot of suggestion that i not added to the applet, because is not ready for release and what is needed right now is a help to understand/create a solution for hard problems as the another issue.

https://github.com/lestcape/Global-AppMenu/issues/1

 The extension required install some packages and also set an environment configuration and also have the latest cinnamon version (the development version).
![captura de pantalla de 2015-04-09 10 14 39](https://cloud.githubusercontent.com/assets/1389572/7069952/48b2671e-dea1-11e4-921a-f5fdeeb1cb85.png)

**Comment by lestcape** [comment]
I add the installation instructions... 
Regards.
