### ISSUE TITLE
sublime and atom menu  very slow

### ISSUE THREAD

**Issue by nyrf** [lestcape/Global-AppMenu#21]
Other applications work well, but when i use sublime and atom, the menu shows very slow.

**Comment by lestcape** [comment]
Yes, there are some incompatible applications, with the cuttler requirements. Normally it's because they not remember the items ids and this forced to create and then destroy the menu in all update. In unity this can be done when the menu will loaded, and when the user show the menu this will be showed perfectly, but in cinnamon this cause some troubles as clutter require the visibility of the actor to then be called the gl implementation. Please see this recently video and compare if this is what happens.

https://www.youtube.com/watch?v=rIIMLlAeXTw

Regards.

**Comment by nyrf** [comment]
I see, thanks.
