### ISSUE TITLE
Show menubar when no windows are open

### ISSUE THREAD

**Issue by bwstrunk2** [lestcape/Global-AppMenu#23]
From using this, it would be nice to have the menubar shown even if there aren't any windows open. This is like Mac OS, where you are at the desktop without any windows open and yet it still shows the menubar for Finder. 

My thought is the same, but for file managers in Linux.

**Comment by lestcape** [comment]
Hi.

I opened an issue that is relate with this here: https://github.com/lestcape/Global-AppMenu/issues/14
I'm disagree with the Mac idea of what will be the default "global menu", because cinnamon have a different conception of the user interation with the desktop. I consider inappropriate don't display a menu when not windows are selected as you.

Regards.

**Comment by bwstrunk2** [comment]
I do agree with you, in terms of how cinnamon has a different concept of what the linux desktop. I think what I really mean is, creating a placeholder when you are at the desktop, basically how Canonical does it in Ubuntu. At times, it looks weird having just a blank panel at the top of the screen. 

![ubuntu_desktop_12 10](https://cloud.githubusercontent.com/assets/14928465/10290868/751806e6-6b5b-11e5-92d1-eb8084b1d9d1.png)

**Comment by lestcape** [comment]
Cinnamon have not support any-more.
