### ISSUE TITLE
Menu not visible with Clementine

### ISSUE THREAD

**Issue by varlesh** [lestcape/Global-AppMenu#26]
![2015-11-29 10 43 56](https://cloud.githubusercontent.com/assets/8083855/11455934/43e2b9a8-9686-11e5-9e8a-36d6a0fbe943.png)
appmenu-qt package installed.
OS: Linux Mint 17.2
DE: Cinnamon 2.6

**Comment by lestcape** [comment]
There are certainly some problems to show the menu.  Restart cinnamon and you will possible see the main menu of clementine (but not complete) and is not free of bugs. I don't know actually why this occurs.

**Comment by varlesh** [comment]
Please show screen. You mean icons on menu or ... ?

**Comment by lestcape** [comment]
Not worried. I try to fix it... there are a problem here:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L3039
This prevent the menu for loads correctly, the code need to be:
```
this._icon.icon_name = name;
```
And then the menu will complete loaded, only in the secuence:
1- Open clementine
2- Restart Cinnamon.

So, the problem is: clementine is slow to export the menu. The solution is wait a little for clementine.

**Comment by lestcape** [comment]
![captura de pantalla de 2015-12-06 04 46 51](https://cloud.githubusercontent.com/assets/1389572/11612950/792c8f78-9bd4-11e5-88fd-e7c0223d5e11.png)

**Comment by lestcape** [comment]
I was wrong clementine is the opposite, is pretty fast, but not matter is fixed here: https://github.com/lestcape/Global-AppMenu/commit/817495daef6b68beb9c1f0c14fa54f8187aeaad1

**Comment by varlesh** [comment]
Thx :+1:
