### ISSUE TITLE
cause crash of SmartGit

### ISSUE THREAD

**Issue by samogot** [lestcape/Global-AppMenu#28]
when i'm using Global-AppMenu, SmartGit crashes right after launch. The support had answered that the reason might be related to this issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=419729

Can it be fixed on your side? Or if it can't - can you add blacklist option not to use your applet for some programs?

**Comment by lestcape** [comment]
Hi i will add an option for active the Jayantana because is pretty buggy. You can restrict other application to not use the menu like the unity implementation. In the gsettings blacklist for example.
http://www.webupd8.org/2013/11/unity-global-menu-can-now-be-disabled.html

Is they are root application you need to do that in the root space.

Regards.

**Comment by lestcape** [comment]
I see what happen, i can not fit it...
