### ISSUE TITLE
Not correctly working on LMDE 2 Betsy

### ISSUE THREAD

**Issue by zevilz** [lestcape/Global-AppMenu#3]
I have LMDE 2 Betsy with Cinnamon 2.4.8
The menu of windows isn't displayed on panel, only a title with icon.
I tried installing indicator-appmenu. No changes and craching on some windows (nemo, terminal etc) with error "this.actor.remove_accessible_state is not a function".
unity-gtk3-module and indicator-appmenu installed from Ubuntu repositories (from 14.04 and 15.04).

**Comment by lestcape** [comment]
indicator-appmenu is in black list on cinnamon, and is not required by the applet... I don't test what could happen on other scenarios yet, but yes, sure will fail, as i only test it on ubuntu, and the last version of cinnamon 2.5.0.
About the application crash, well, this also occurs to me when i try restart cinnamon, not on other cases... Apparently some proxies are not properly destroyed in this case and cause the crash, i don't know yet. as this also occurs some time without the applet. I think that could be my hardware also. When I changed the applet to the version 0.1 will be because i think that is stable to be used on cinnamon 2.0 or higher, this will not mean that will work on other system different than Mint (as ubuntu derivative) for ubuntu 14.04, just that the probably cause will be the system and not the cinnamon version... Then this will be the moment to try to fix any problem related to the specific distro, now there are a lot of causes and is difficult.

I will tell you.
Thanks.

**Comment by lestcape** [comment]
The problem about actor.remove_accessible_state is cinnamon version and can be fixed just open the file configurableMenus.js and commented the 3 lines with:
this.actor.remove_accessible_state(Atk.StateType.CHECKED);
need to be:
//this.actor.remove_accessible_state(Atk.StateType.CHECKED);

But could occurs more things...

**Comment by zevilz** [comment]
Whether the applet due to the lack of some packages in system can incorrectly work? Maybe will earn if to establish them. I would like to learn what packages uses an applet for the work. It maybe would help to solve a problem.

P.S. and still I saw on a github that the applet is based on maximus extension. It too works not correctly. Windows on all screen the heading is removed, but on the panel there is no window title and the buttons. It seems that for it too something isn't enough.

**Comment by lestcape** [comment]
Not, the applet not currently use the maximum extension. I will add this when the applet will be stable. The maximum extension code is inside the applet, but is not used. And will be enable by users as a decision, because yes, can cause serious troubles, on some environments. I probably I found the apparently cause of the application crash.

On dbusmenu.js

Make a comment of this lines

//for (let x = 0; x < 1024; x++) { init_menu.push(x); }
            //this._proxy_menu.EndRemote(init_menu,
            //    Lang.bind(this, function(result, error) {})); // Nothing to do

**Comment by zevilz** [comment]
without changes
tried with trusty and vivid packages

**Comment by lestcape** [comment]
ok, my problem about application crash was more difficul. Is because i need to call End the same number of times that i call start
https://wiki.gnome.org/Projects/GLib/GApplication/DBusAPI

and if cinnamon restart without give me the possibility of call end, then this will be problematic... This is why some time the applet crash the gtk application and some time not.

I will see if i can add compatibility with the oldest cinnamon version latter and resolve this problem

**Comment by lestcape** [comment]
maybe you will be happy now. Test it...

Regards.
