### ISSUE TITLE
Theme settings mismatch

### ISSUE THREAD

**Issue by oliveiraev** [lestcape/Global-AppMenu#33]
The applet fits on 'Cinnamon' and 'Linux Mint' themes but doesnot on 'Mint-X' or 'Numix' variants

![captura de tela de 2016-03-16 13 06 25](https://cloud.githubusercontent.com/assets/320460/13820704/3c1a2304-eb7d-11e5-9f05-88d4f1112df5.png)

Already had this issue but I don't remember how to fix it

**Comment by lestcape** [comment]
The best that we can do, is try to support the standards themes. The theme is for a component, not the component is for the theme. Anyway, is possible try to support more theme variants, but this have inconvenience, because the only option is in a hard way. So, we need to decide if we want to hard-code the theme properties or instead, allow to be configured by the author of the theme. Both things is not possible.

**Comment by oliveiraev** [comment]
Melange/Looking-Glass is painful. I couldn't even figure out what kind of object are the menuitems.

Trying to pick up the colors and find'em on the theme CSS wasn't helpful too.

If you take a closer look, even 'Linux Mint' theme mismatches color...
![color-mismatch](https://cloud.githubusercontent.com/assets/320460/13879175/cfb214c8-ecf4-11e5-8bb9-ad02fbdc0dff.png)
... and height, on hover...
![hover-height-mismatch](https://cloud.githubusercontent.com/assets/320460/13879180/dd8583f0-ecf4-11e5-917d-6ddf67cad020.png)

I agree that themes should define component styles but, several of them were written for older versions of Cinnamon and before this applet. If I got any clue about the components CSS names I could force some settings to match better and more themes, at least for a while.

**Comment by lestcape** [comment]
The menu items inside the cinnamon panel is my invention. Normally, the way is add normal actors, not menu items, i force some items to resigned an style, probably the solution will be here: https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L5772-L5774 

or also here, where i thing there are an error:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L6052

because i need to set the style not add the style. I will see what can i do latter.

**Comment by oliveiraev** [comment]
After your tips I've checked out some commits.

06910e661 goes **very** well...
![cinnamon-numix-globalmenu](https://cloud.githubusercontent.com/assets/320460/13921482/d9e700f2-ef56-11e5-946a-a1bf78a32fda.png)

b00db17e broke the menu. Now we have a starting point. I wish to collaborate more but, I'm starting with cinnamon/gnome extensions and have no much available time :cry:

**Comment by lestcape** [comment]
Can you see if the problem was resolved?
https://github.com/lestcape/Global-AppMenu/commit/8a54ed6fb1dff50d0e9ff057fcda654f9a9ba183

**Comment by oliveiraev** [comment]
Great! Sorry for delay. Tested with mint-y and numix and everything is OK now.

**Comment by lestcape** [comment]
Good!!
