### ISSUE TITLE
Is it possible to include GM in Cinnamon officially?

### ISSUE THREAD

**Issue by alxgvr** [lestcape/Global-AppMenu#36]
Hi. I love global menu, and thank you for this applet!
Your applet keeps me on Cinnamon (without it I would switch back to Unity).

Can you suggest cinnamon developers to include your beautifull Global Menu applet to official Cinnamon applets pack?
Like MATE did with TopMenu.

**Comment by lestcape** [comment]
Yes it's possible to include it officially, but only if the cinnamon devs want. You need to speak with him... But probably, it's better create an issue on cinnamon dev site: https://github.com/linuxmint/Cinnamon/issues

Anyway, keep this working on all distros, it's just not really easy as this is not the applet itself and like the applet is thinking to work with the canonical implementation and like in some distros they think that the canonical implementation it's only for unity desktop (maybe because the packages names contains "unity"). Will be then really difficult resolve this situation and you will try to included an applet without support in several distros...

**Comment by lestcape** [comment]
You need to read this anyway:
https://github.com/linuxmint/Cinnamon/issues/551
https://github.com/linuxmint/Cinnamon/issues/3032
