### ISSUE TITLE
Not working in Mint 18

### ISSUE THREAD

**Issue by alxgvr** [lestcape/Global-AppMenu#37]
Only one app, where Global menu applet works - is Firefox.
Not working with other apps in Mint 18

**Comment by lestcape** [comment]
@alxgvr sorry, but you install all packages thats this needed?
In Mint there are not installed by default, at last:

sudo apt-get install unity-gtk2-module unity-gtk3-module

Could be that you need other important packages, i dont know in the case of Mint...

**Comment by lestcape** [comment]
http://www.webupd8.org/2015/05/global-menu-applet-for-cinnamon-desktop.html

**Comment by alxgvr** [comment]
Yes, it helped, thank you.
Just missed that:  sudo apt-get install unity-gtk2-module unity-gtk3-module appmenu-qt appmenu-qt5

**Comment by lestcape** [comment]
https://solus-project.com/forums/viewtopic.php?t=1175

Don't worried about beta, the beta, it`s because this extension use a non official cinnamon api, to display several menu at the same time and not only one as cinnamon. So, a cinnamon change could break this extension in any moment. This not mean that have any problem. The only conflict it`s with jayantana, and is also a problem in unity, so not any news...
