### ISSUE TITLE
Menus is not clickable

### ISSUE THREAD

**Issue by rilian-la-te** [lestcape/Global-AppMenu#4]
Just installed Cinnamon to test your applet.

Menus is shown now, but it is not clickable. Instead, click is routed into background and activated windows below.

Arch Linux. Cinnamon 2.4.8.

**Comment by PHPJosh** [comment]
I can confirm this on Linux Mint 17.1

**Comment by lestcape** [comment]
I can confirm this also, for some reason this occurs on my mint installation and arch but not in ubuntu, jejeje... The problem is my new api to show multiples menus over cinnamon. Aparently the are a problem with my external menumanager patch... I will see how i can fix this... any way i have more bugs that need to be solved... thanks.

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/commit/0fd9c646f643370027269c77d59e50c067605619
