### ISSUE TITLE
Prevent panel auto-hide when a menu is open

### ISSUE THREAD

**Issue by viggy96** [lestcape/Global-AppMenu#42]
The title, basically, This enhancement would be nice.

**Comment by lestcape** [comment]
Yes, but basically this will required some work on the cinnamon side, because this is a task of the panel and not of the applet. As this extension don't use the cinnamon api, and not follow the cinnamon focus criteria (close a popup menu if another it's open) will be a little complex the interaction with the panel. I think there are not any easy function to prevent a panel autohide in the cinnamon side. If i will do that, need to be in a non invasive way (calling a cinnamon function), because in an invasive way (hacked the panel code) i will create a dependency of the internal code of the cinnamon panel... I don't have time to follow all cinnamon panel changes of his internal code. In the last 4 release cinnamon change his way of how the panels are i.e. don't look for now a good thing to be done.

**Comment by lestcape** [comment]
I hope this not happen i add a lot of checks... Done..
