### ISSUE TITLE
Visual issue.

### ISSUE THREAD

**Issue by rilian-la-te** [lestcape/Global-AppMenu#45]
![screenshot from 2016-12-16 00-01-48](https://cloud.githubusercontent.com/assets/1329638/21241992/98548f84-c32b-11e6-8615-583b92a98733.png)

Name must be visible, but last letter is cut in it. Treshold in settings - 30 symbols.

**Comment by lestcape** [comment]
Hi @rilian-la-te i known that, but for definition, the application name of the cinnamon menu are also cut off. The windows labels are also cut off, really in cinnamon all it's cut off...

This is how the things are, take a look: https://github.com/linuxmint/Cinnamon/pull/6093

I don't want to be who change that...

Please see:
https://github.com/lestcape/Global-AppMenu/issues/10
https://github.com/lestcape/Global-AppMenu/issues/43
https://github.com/lestcape/Global-AppMenu/issues/44

**Comment by rilian-la-te** [comment]
Nemo's name is also cut down

**Comment by lestcape** [comment]
:) ?? I don't know the long name then...

**Comment by rilian-la-te** [comment]
All names is cut down for some letters for me. I will show you Nero screen

**Comment by rilian-la-te** [comment]
![screenshot from 2016-12-17 17-45-34](https://cloud.githubusercontent.com/assets/1329638/21287622/16d387d0-c489-11e6-8780-bb57c6f7d757.png)

Here is cutted Nemo. It is not OK for me, I reopening it.

**Comment by lestcape** [comment]
Yes and what you think will be ok? The problem it's that i need to have a limit, because some applications name are really long and of course this will break the panel. so?

**Comment by rilian-la-te** [comment]
I think will be ok, if only long names will cut. But not short, as Nemo (Limit is 30 symbols in my app).

**Comment by lestcape** [comment]
mmm, thats not occurs to me the las letter it's hide, but the space for the letter it's there... What cinnamon theme you use?

**Comment by lestcape** [comment]
Thats occurs for the default cinnamon theme? If not, this is a theme issue.

**Comment by rilian-la-te** [comment]
![screenshot from 2016-12-17 18-30-59](https://cloud.githubusercontent.com/assets/1329638/21287914/6e52838e-c48f-11e6-82d7-2e8fae83388b.png)
With default also occurs.

**Comment by lestcape** [comment]
This is what i supposes that user see:
![gg](https://cloud.githubusercontent.com/assets/1389572/21287980/2d31dd70-c43d-11e6-8b8a-6bea61cf7fd2.png)

**Comment by rilian-la-te** [comment]
Do you think it is correct for gedit for example? I think, this short names
should be shown fully without shade.

**Comment by lestcape** [comment]
Yes, because the text it's reactive and have a different behavior, so if needed a way to separate the application name from the menu or users will hide the menu clicking where it's not the place.

**Comment by rilian-la-te** [comment]
May separate it by add some spaces, if size of name is small?

**Comment by lestcape** [comment]
As i need to cut of the string and create a separation for that, and like i don't what to let pango decide where it's convenient create the "..." i will make my own component to let user see more characters and also decide to not have a long name (the length of the app text) and also don't need to have unnecessary spaces between things, making the menu more compacted.

In others words:
I don't want a log name, because then the menu will show in different places, base on the length of the app name. That cause that we need to move the mouse to a different position base on the length of the text and this is not convenient for usage.

How i will want to show more characters and not the pango "...", I create my own way to display this. Of course this is not perfectly.

**Comment by lestcape** [comment]
"May separate it by add some spaces, if size of name is small?": Yes theme author can do do if they want, harcode this inside the extension it's not a good way to do that, or will be forced for all themes and what will be the idea of have themes then?

**Comment by rilian-la-te** [comment]
What about setting? Like "does not cut application name?"

**Comment by lestcape** [comment]
Not cut application name for me it's not an option. Could be an option don't degraded the text, and use a more big value in the settings for the number of the characters that will be allowed to show, but not a big, big one. I don't want to break the panel.

**Comment by rilian-la-te** [comment]
Yes, I am like your suggestion, so names like Nemo or gedit will not be degraded:)

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/commit/5f6237e0094d620ed76e7a2370bcf417af48101b

**Comment by rilian-la-te** [comment]
Thanks, but MATE Terminal is always cut:( Even if 60 symbols treshold:( Can you look for it?

**Comment by lestcape** [comment]
I can not resolve this problem:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L1906-L1908

Pango not return the real text width, just it's giving you an approximation of a character width, i use also the digit width because the character width always it's less that the text, but if you have characters like "m" in the name, of course the size will be more than that.
