### ISSUE TITLE
Boxpointers in 3.2!?

### ISSUE THREAD

**Issue by feren** [lestcape/Global-AppMenu#46]
Somehow, if you use a theme with boxpointer support on Cinnamon 3.2 in conjunction with this applet, and then right click on Global AppMenu while it has no menu items, the menu has boxpointers... in Cinnamon 3.2 (Ok then)

**Comment by lestcape** [comment]
Yes @feren, also configurable menu has boxpointers: I don't remove this feature from my code and i will not remove it. Will be also wrong remove the boxpointer support in a theme, because you will lost compatibility with older cinnamon versions. Anyway, this is a thrid-party applet, and have not support for themes as default, if you want support it in your themes, you will need to explicit add support for it.

**Comment by feren** [comment]
OK, good to know, though, I'm not on the Linux Machine right now, but is there a toggle for boxpointers in menus on this applet like there is on ConfigurableMenu?

**Comment by lestcape** [comment]
Yes there are a toggle, just there are not a way for users to access it... You will need that?

**Comment by lestcape** [comment]
Sorry. it's there. I'm not in cinnamon right now also. But the option to disable the boxpointer it's there.

**Comment by feren** [comment]
@lestcape Thanks, just was thinking for consistency, afterall, the amount of people complaining about it in Windows 10...
