### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by enep** [lestcape/Global-AppMenu#52]
After the upgrade of Linux Mint cinnamon 18.2
The applet is launched. Cinnamon Version 3.4.3

**Comment by lestcape** [comment]
https://github.com/lestcape/Global-AppMenu/issues/51
https://github.com/lestcape/Global-AppMenu/issues/50

**Comment by enep** [comment]
in the future will work?

**Comment by lestcape** [comment]
I don' t know. For x11, is just a thing that someone want to update it(few minutes, maybe hours). For Wayland  this depend of the gtk developers or otherwise is needed a crude hack that also i think will be very difficult or impossible, because is hack a gdk function in a gtk module (unity-gtk-module).

I discontinue the extension for non technical reasons. My spices account was violated and in cinnamon there are not way to have a real third-party extension. All extensions are now controlled by "cinnamon". The violation of my spices account, not matter to me really, because they give me the chance to  delete my work, but as i say actually there are no way to have REAL third-party extensions in cinnamon and without that i will not make anything to cinnamon.

Sorry for the inconvenient.
